test:
  adapter: oracle_enhanced
  database: 'dm02-scan.prod.lan:7381/oratest' 
  username: msexton1
  password: 

production:
  adapter: oracle_enhanced
  database: 'dm01-scan.prod.lan:7381/oraprod' 
  username: msexton1
  password:
