TAS: http://www.mrt.tas.gov.au/web-services/wfs
NSW: http://gsnsw.arrc.csiro.au/gsnsw-earthresource/wfs
WA: http://geossdi.dmp.wa.gov.au/services/wfs
VIC: http://geology.data.vic.gov.au/nvcl/wfs
SA: https://sarigdata.pir.sa.gov.au/nvcl/geoserver/wfs
NT: http://geology.data.nt.gov.au:80/geoserver/wfs
QLD: 